import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  intro: ['index', 'tos', 'privacy', 'trademark', 'contact'],
  discord: [
    {
      type: 'category',
      label: 'JSTimerBot',
      link: {
        type: 'doc',
        id: 'discord/timer/index'
      },
      items: [
        'discord/timer/index',
        {
          type: 'category',
          label: 'コマンド',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'discord/timer/commands/index'
          },
          items: [
            'discord/timer/commands/set',
            'discord/timer/commands/repeat',
            'discord/timer/commands/cancel',
            'discord/timer/commands/list',
            'discord/timer/commands/test'
          ]
        },
        'discord/timer/channel',
        'discord/timer/mention',
        'discord/timer/changelog'
      ]
    }
  ],
  api: [{type: 'autogenerated', dirName: 'api'}]
};

export default sidebars;
