import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  intro: ['index', 'tos', 'privacy', 'trademark', 'contact'],
  discord: [
    'discord/index',
    {
      type: 'category',
      label: 'JSTimerBot',
      link: {
        type: 'doc',
        id: 'discord/timer/index'
      },
      items: [
        'discord/timer/index',
        'discord/timer/changelog',
        'discord/timer/channel',
        'discord/timer/mention',
        {
          type: 'category',
          label: 'コマンド',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'discord/timer/commands/index'
          },
          items: [
            'discord/timer/commands/set',
            'discord/timer/commands/repeat',
            'discord/timer/commands/cancel',
            'discord/timer/commands/list',
            'discord/timer/commands/test'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: '[非公式] 整地鯖Bot',
      link: {
        type: 'doc',
        id: 'discord/seichi/index'
      },
      items: [
        'discord/seichi/index',
        'discord/seichi/changelog',
        {
          type: 'category',
          label: 'コマンド',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'discord/seichi/commands/index'
          },
          items: [
            'discord/seichi/commands/ranking',
            'discord/seichi/commands/filter',
            'discord/seichi/commands/player',
            'discord/seichi/commands/map',
            'discord/seichi/commands/crop',
            'discord/seichi/commands/playerlist',
            'discord/seichi/commands/search',
            'discord/seichi/commands/schedule'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'poker',
      link: {
        type: 'doc',
        id: 'discord/poker/index'
      },
      items: [
        'discord/poker/index'
      ]
    }
  ],
  api: [{type: 'autogenerated', dirName: 'api'}]
};

export default sidebars;
